version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  automerged_updates:
    - match:
        dependency_type: "all"
        update_type: "security:patch"
    - match:
        dependency_type: "all"
        update_type: "semver:patch"
