package io.rtcore.sip.proxy.http.netty;

import java.net.URI;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalInt;

import org.immutables.value.Value;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@Value.Immutable
@JsonSerialize
@JsonInclude(value = Include.NON_DEFAULT)
public interface Problem {

  /**
   * "type" (string) - A URI reference [RFC3986] that identifies the problem type. This
   * specification encourages that, when dereferenced, it provide human-readable documentation for
   * the problem type (e.g., using HTML [W3C.REC-html5-20141028]). When this member is not present,
   * its value is assumed to be "about:blank".
   */

  Optional<URI> type();

  /**
   * "title" (string) - A short, human-readable summary of the problem type. It SHOULD NOT change
   * from occurrence to occurrence of the problem, except for purposes of localization (e.g., using
   * proactive content negotiation; see [RFC7231], Section 3.4).
   */

  Optional<String> title();

  /**
   * "status" (number) - The HTTP status code ([RFC7231], Section 6) generated by the origin server
   * for this occurrence of the problem.
   */

  OptionalInt status();

  /**
   * "detail" (string) - A human-readable explanation specific to this occurrence of the problem.
   */

  Optional<String> detail();

  /**
   * "instance" (string) - A URI reference that identifies the specific occurrence of the problem.
   * It may or may not yield further information if dereferenced.
   */

  Optional<URI> instance();

  /**
   * 
   */

  @JsonAnyGetter
  Map<String, JsonNode> properties();

}
